// --CONSUMER----------------------------------------------------

//TODO: decide after looking into the login/signup logic
// // CONSUMER REGISTRATION
// export const CONSUMER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
// export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
// export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// // CONSUMER LOGIN
// export const CONSUMER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
// export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
// export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
// export const USER_LOGOUT = 'USER_LOGOUT';

// CONSUMER UPDATE
export const CONSUMER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const CONSUMER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const CONSUMER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH CONSUMERS
export const FETCH_CONSUMER_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_CONSUMER_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_CONSUMER_FAIL = 'CREATE_USERS_FAIL';

// CONSUMER PROFILE: fetching specific consumer
export const CONSUMER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const CONSUMER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const CONSUMER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

// --CREATOR----------------------------------------------------

//TODO: decide after looking into the login/signup logic
//USER REGISTRATION
export const CREATOR_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const CREATOR_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

//USER PROFILE
export const CREATOR_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const CREATOR_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const CREATOR_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//USER UPDATE
export const CREATOR_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const CREATOR_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const CREATOR_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH USERS
export const FETCH_CREATOR_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_CREATOR_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_CREATOR_FAIL = 'CREATE_USERS_FAIL';

// --QUIZ----------------------------------------------------

// CREATE QUIZ
export const CREATE_QUIZ_REQUEST = 'CREATE_QUIZ_REQUEST';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAIL = 'CREATE_QUIZ_FAIL';

// FETCH QUIZ
export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAIL = 'CREATE_QUIZ_FAIL';

// DELETE QUIZ
export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_FAIL = 'DELETE_QUIZ_FAIL';

// QUIZ DETAILS: for fetching one quiz
export const QUIZ_DETAIL_REQUEST = 'QUIZ_DETAIL_REQUEST';
export const QUIZ_DETAIL_SUCCESS = 'QUIZ_DETAIL_SUCCESS';
export const QUIZ_DETAIL_FAIL = 'QUIZ_DETAIL_FAIL';

// UPDATE QUIZ
export const QUIZ_UPDATE_REQUEST = 'QUIZ_UPDATE_REQUEST';
export const QUIZ_UPDATE_SUCCESS = 'QUIZ_UPDATE_SUCCESS';
export const QUIZ_UPDATE_FAIL = 'QUIZ_UPDATE_FAIL';

// --PLATFORM----------------------------------------------------

// CREATE PLATFORM
export const CREATE_PLATFORM_REQUEST = 'CREATE_PLATFORM_REQUEST';
export const CREATE_PLATFORM_SUCCESS = 'CREATE_PLATFORM_SUCCESS';
export const CREATE_PLATFORM_FAIL = 'CREATE_PLATFORM_FAIL';

// FETCH PLATFORM
export const FETCH_PLATFORM_REQUEST = 'FETCH_PLATFORM_REQUEST';
export const FETCH_PLATFORM_SUCCESS = 'FETCH_PLATFORM_SUCCESS';
export const FETCH_PLATFORM_FAIL = 'CREATE_PLATFORM_FAIL';

// DELETE PLATFORM
export const DELETE_PLATFORM_REQUEST = 'DELETE_PLATFORM_REQUEST';
export const DELETE_PLATFORM_SUCCESS = 'DELETE_PLATFORM_SUCCESS';
export const DELETE_PLATFORM_FAIL = 'DELETE_PLATFORM_FAIL';

// PLATFORM DETAILS
export const PLATFORM_DETAIL_REQUEST = 'PLATFORM_DETAIL_REQUEST';
export const PLATFORM_DETAIL_SUCCESS = 'PLATFORM_DETAIL_SUCCESS';
export const PLATFORM_DETAIL_FAIL = 'PLATFORM_DETAIL_FAIL';

//UPDATE PLATFORM
export const PLATFORM_UPDATE_REQUEST = 'PLATFORM_UPDATE_REQUEST';
export const PLATFORM_UPDATE_SUCCESS = 'PLATFORM_UPDATE_SUCCESS';
export const PLATFORM_UPDATE_FAIL = 'PLATFORM_UPDATE_FAIL';